---
- hosts: webserver
  become: yes
  vars:
    start_time: "{{ lookup('pipe', 'date +%s') }}"
  tasks:
    - name: Record overall start time
      set_fact:
        overall_start_time: "{{ lookup('pipe', 'date +%s') }}"
    - name: Measure network latency to the target
      command: ping -c 4 192.168.0.144
      register: ping_result
      failed_when: ping_result.rc != 0 and ping_result.stdout.find('100% packet loss') == -1


    - name: Measure network latency to the target
      command: "ping -c 4 192.168.0.144"
      register: latency
      changed_when: false

    - name: Display raw ping output
      debug:
        msg: "Ping output: {{ latency.stdout }}"

    - name: Calculate and display network latency
      debug:
        msg: >-
          {% set rtt_times = latency.stdout | regex_findall('time=(\\d+\\.\\d+)') | map('float') %}
          {% if rtt_times | length > 0 %}
          Network Latency (RTT) to 192.168.0.144: {{ rtt_times | sum / rtt_times | length }} ms (average of 4 pings)
          {% else %}
          Network Latency: Unable to retrieve latency values. Please check the network connection.
          {% endif %}

    - name: Ensure Docker is installed
      set_fact:
        task_start_time: "{{ lookup('pipe', 'date +%s') }}"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      register: docker_install_result

    - name: Display time taken for Docker installation
      debug:
        msg: "Time taken for Docker installation: {{ (lookup('pipe', 'date +%s') | int) - task_start_time | int }} seconds"

    - name: Install Python pip
      set_fact:
        task_start_time: "{{ lookup('pipe', 'date +%s') }}"

    - apt:
        name: python3-pip
        state: present
      register: pip_install_result

    - name: Display time taken for pip installation
      debug:
        msg: "Time taken for pip installation: {{ (lookup('pipe', 'date +%s') | int) - task_start_time | int }} seconds"

    - name: Install docker module for Python
      set_fact:
        task_start_time: "{{ lookup('pipe', 'date +%s') }}"

    - apt:
        name: python3-docker
        state: present
      register: docker_module_result

    - name: Display time taken for docker module installation
      debug:
        msg: "Time taken for docker module installation: {{ (lookup('pipe', 'date +%s') | int) - task_start_time | int }} seconds"

    - name: Create and start cafe web container
      set_fact:
        task_start_time: "{{ lookup('pipe', 'date +%s') }}"

    - docker_container:
        name: cafe_web
        image: vijeth2001/cafestatic:v1
        ports:
          - "1020:80"
        state: started
      register: cafe_container_result

    - name: Display time taken to create and start cafe container
      debug:
        msg: "Time taken to start cafe web container: {{ (lookup('pipe', 'date +%s') | int) - task_start_time | int }} seconds"

    - name: Record overall end time
      set_fact:
        overall_end_time: "{{ lookup('pipe', 'date +%s') }}"

    - name: Display total deployment time
      debug:
        msg: "Total deployment time: {{ (overall_end_time | int) - (overall_start_time | int) }} seconds"
